
package Image::ExifTool::DarwinCore;

use strict;
use vars qw($VERSION);
use Image::ExifTool::XMP;

$VERSION = '1.08';

my %dateTimeInfo = (
    Writable     => 'date',
    Shift        => 'Time',
    PrintConv    => '$self->ConvertDateTime($val)',
    PrintConvInv => '$self->InverseDateTime($val,undef,1)',
);

my %materialSample = (
    STRUCT_NAME      => 'DarwinCore MaterialSample',
    NAMESPACE        => 'dwc',
    materialSampleID => {},
);

my %event = (
    STRUCT_NAME  => 'DarwinCore Event',
    NAMESPACE    => 'dwc',
    day          => { Writable => 'integer', Groups => { 2 => 'Time' } },
    earliestDate => { %dateTimeInfo, Groups => { 2 => 'Time' } },
    endDayOfYear => { Writable => 'integer', Groups => { 2 => 'Time' } },
    eventDate    => { %dateTimeInfo, Groups => { 2 => 'Time' } },
    eventID      =>
      { Avoid => 1, Notes => 'avoided in favor of XMP-iptcExt:EventID' },
    eventRemarks => { Writable => 'lang-alt' },
    eventTime    => {
        Groups   => { 2 => 'Time' },
        Writable => 'string',
        Shift    => 'Time',
        ValueConv    => 'Image::ExifTool::XMP::ConvertXMPDate($val)',
        PrintConv    => '$self->ConvertDateTime($val)',
        ValueConvInv => 'Image::ExifTool::XMP::FormatXMPDate($val) or $val',
        PrintConvInv => q{
            my $v = $self->InverseDateTime($val,undef,1);
            undef $Image::ExifTool::evalWarning;
            return $v if $v;
            # allow time-only values by adding dummy date (thanks Herb)
            my $v = $self->InverseDateTime("2000:01:01 $val",undef,1);
            undef $Image::ExifTool::evalWarning;
            return $v if $v and $v =~ s/.* //;  # strip off dummy date
            $Image::ExifTool::evalWarning = 'Invalid date/time or time-only value (use HH:MM:SS[.ss][+/-HH:MM|Z])';
            return undef;
        },
    },
    fieldNotes        => {},
    fieldNumber       => {},
    habitat           => {},
    latestDate        => { %dateTimeInfo, Groups => { 2 => 'Time' } },
    month             => { Writable => 'integer', Groups => { 2 => 'Time' } },
    parentEventID     => {},
    samplingEffort    => {},
    samplingProtocol  => {},
    sampleSizeValue   => {},
    sampleSizeUnit    => {},
    startDayOfYear    => { Writable => 'integer', Groups => { 2 => 'Time' } },
    verbatimEventDate => { Groups   => { 2 => 'Time' } },
    year              => { Writable => 'integer', Groups => { 2 => 'Time' } },
    eventType         => {},
);

%Image::ExifTool::DarwinCore::Main = (
    GROUPS    => { 0 => 'XMP', 1 => 'XMP-dwc', 2 => 'Other' },
    NAMESPACE => 'dwc',
    WRITABLE  => 'string',
    NOTES     => q{
        Tags defined in the Darwin Core (dwc) XMP namespace.  See
        L<http://rs.tdwg.org/dwc/index.htm> for the official specification.
    },
    Event => {
        Name     => 'DCEvent',
        FlatName => 'Event',
        Struct   => \%event,
    },
    EventEventDate    => { Name   => 'EventDate',    Flat => 1 },
    EventEventID      => { Name   => 'EventID',      Flat => 1 },
    EventEventRemarks => { Name   => 'EventRemarks', Flat => 1 },
    EventEventTime    => { Name   => 'EventTime',    Flat => 1 },
    FossilSpecimen    => { Struct => \%materialSample },
    GeologicalContext => {
        FlatName => '',
        Struct   => {
            STRUCT_NAME                  => 'DarwinCore GeologicalContext',
            NAMESPACE                    => 'dwc',
            bed                          => {},
            earliestAgeOrLowestStage     => {},
            earliestEonOrLowestEonothem  => {},
            earliestEpochOrLowestSeries  => {},
            earliestEraOrLowestErathem   => {},
            earliestPeriodOrLowestSystem => {},
            formation                    => {},
            geologicalContextID          => {},
            group                        => {},
            highestBiostratigraphicZone  => {},
            latestAgeOrHighestStage      => {},
            latestEonOrHighestEonothem   => {},
            latestEpochOrHighestSeries   => {},
            latestEraOrHighestErathem    => {},
            latestPeriodOrHighestSystem  => {},
            lithostratigraphicTerms      => {},
            lowestBiostratigraphicZone   => {},
            member                       => {},
        },
    },
    GeologicalContextBed       => { Name => 'GeologicalContextBed', Flat => 1 },
    GeologicalContextFormation =>
      { Name => 'GeologicalContextFormation', Flat => 1 },
    GeologicalContextGroup  => { Name => 'GeologicalContextGroup',  Flat => 1 },
    GeologicalContextMember => { Name => 'GeologicalContextMember', Flat => 1 },
    HumanObservation        => { Struct => \%event },
    Identification          => {
        FlatName => '',
        Struct   => {
            STRUCT_NAME      => 'DarwinCore Identification',
            NAMESPACE        => 'dwc',
            dateIdentified   => { %dateTimeInfo, Groups => { 2 => 'Time' } },
            identificationID => {},
            identificationQualifier          => {},
            identificationReferences         => {},
            identificationRemarks            => {},
            identificationVerificationStatus => {},
            identifiedBy                     => {},
            typeStatus                       => {},
            identifiedByID         => {},
            verbatimIdentification => {},
        },
    },
    LivingSpecimen                 => { Struct => \%materialSample },
    MachineObservation             => { Struct => \%event },
    MaterialSample                 => { Struct => \%materialSample },
    MaterialSampleMaterialSampleID => { Name => 'MaterialSampleID', Flat => 1 },
    MeasurementOrFact              => {
        FlatName => '',
        Struct   => {
            STRUCT_NAME               => 'DarwinCore MeasurementOrFact',
            NAMESPACE                 => 'dwc',
            measurementAccuracy       => { Format => 'real' },
            measurementDeterminedBy   => {},
            measurementDeterminedDate =>
              { %dateTimeInfo, Groups => { 2 => 'Time' } },
            measurementID       => {},
            measurementMethod   => {},
            measurementRemarks  => {},
            measurementType     => {},
            measurementUnit     => {},
            measurementValue    => {},
            parentMeasurementID => {},
        },
    },
    Occurrence => {
        Struct => {
            STRUCT_NAME             => 'DarwinCore Occurrence',
            NAMESPACE               => 'dwc',
            associatedMedia         => {},
            associatedOccurrences   => {},
            associatedReferences    => {},
            associatedSequences     => {},
            associatedTaxa          => {},
            behavior                => {},
            catalogNumber           => {},
            disposition             => {},
            establishmentMeans      => {},
            individualCount         => {},
            individualID            => {},
            lifeStage               => {},
            occurrenceDetails       => {},
            occurrenceID            => {},
            occurrenceRemarks       => {},
            occurrenceStatus        => {},
            organismQuantity        => {},
            organismQuantityType    => {},
            otherCatalogNumbers     => {},
            preparations            => {},
            previousIdentifications => {},
            recordedBy              => {},
            recordNumber            => {},
            reproductiveCondition   => {},
            sex                     => {},
            degreeOfEstablishment          => {},
            georeferenceVerificationStatus => {},
            pathway                        => {},
            recordedByID                   => {},
            caste                          => {},
            vitality                       => {},
        },
    },
    OccurrenceOccurrenceDetails => { Name => 'OccurrenceDetails', Flat => 1 },
    OccurrenceOccurrenceID      => { Name => 'OccurrenceID',      Flat => 1 },
    OccurrenceOccurrenceRemarks => { Name => 'OccurrenceRemarks', Flat => 1 },
    OccurrenceOccurrenceStatus  => { Name => 'OccurrenceStatus',  Flat => 1 },
    Organism                    => {
        Struct => {
            STRUCT_NAME             => 'DarwinCore Organism',
            NAMESPACE               => 'dwc',
            associatedOccurrences   => {},
            associatedOrganisms     => {},
            organismID              => {},
            organismName            => {},
            organismRemarks         => {},
            organismScope           => {},
            previousIdentifications => {},
        },
    },
    OrganismOrganismID      => { Name   => 'OrganismID',      Flat => 1 },
    OrganismOrganismName    => { Name   => 'OrganismName',    Flat => 1 },
    OrganismOrganismRemarks => { Name   => 'OrganismRemarks', Flat => 1 },
    OrganismOrganismScope   => { Name   => 'OrganismScope',   Flat => 1 },
    PreservedSpecimen       => { Struct => \%materialSample },
    Record                  => {
        Struct => {
            STRUCT_NAME          => 'DarwinCore Record',
            NAMESPACE            => 'dwc',
            basisOfRecord        => {},
            collectionCode       => {},
            collectionID         => {},
            dataGeneralizations  => {},
            datasetID            => {},
            datasetName          => {},
            dynamicProperties    => {},
            informationWithheld  => {},
            institutionCode      => {},
            institutionID        => {},
            ownerInstitutionCode => {},
        },
    },
    ResourceRelationship => {
        FlatName => '',
        Struct   => {
            STRUCT_NAME                 => 'DarwinCore ResourceRelationship',
            NAMESPACE                   => 'dwc',
            relatedResourceID           => {},
            relationshipAccordingTo     => {},
            relationshipEstablishedDate =>
              { %dateTimeInfo, Groups => { 2 => 'Time' } },
            relationshipOfResource   => {},
            relationshipRemarks      => {},
            resourceID               => {},
            resourceRelationshipID   => {},
            relationshipOfResourceID => {},
        },
    },
    Taxon => {
        Struct => {
            STRUCT_NAME              => 'DarwinCore Taxon',
            NAMESPACE                => 'dwc',
            acceptedNameUsage        => {},
            acceptedNameUsageID      => {},
            class                    => {},
            family                   => {},
            genus                    => {},
            higherClassification     => {},
            infraspecificEpithet     => {},
            cultivarEpithet          => {},
            kingdom                  => {},
            nameAccordingTo          => {},
            nameAccordingToID        => {},
            namePublishedIn          => {},
            namePublishedInID        => {},
            namePublishedInYear      => {},
            nomenclaturalCode        => {},
            nomenclaturalStatus      => {},
            order                    => {},
            originalNameUsage        => {},
            originalNameUsageID      => {},
            parentNameUsage          => {},
            parentNameUsageID        => {},
            phylum                   => {},
            scientificName           => {},
            scientificNameAuthorship => {},
            scientificNameID         => {},
            specificEpithet          => {},
            subgenus                 => {},
            taxonConceptID           => {},
            taxonID                  => {},
            taxonRank                => {},
            taxonRemarks             => {},
            taxonomicStatus          => {},
            verbatimTaxonRank        => {},
            vernacularName           => { Writable => 'lang-alt' },
            superFamily              => {},
            subFamily                => {},
            tribe                    => {},
            subTribe                 => {},
            genericName              => {},
            infragenericEpithet      => {},
        },
    },
    TaxonTaxonConceptID => { Name => 'TaxonConceptID', Flat => 1 },
    TaxonTaxonID        => { Name => 'TaxonID',        Flat => 1 },
    TaxonTaxonRank      => { Name => 'TaxonRank',      Flat => 1 },
    TaxonTaxonRemarks   => { Name => 'TaxonRemarks',   Flat => 1 },
    dctermsLocation     => {
        Name     => 'DCTermsLocation',
        Groups   => { 2 => 'Location' },
        FlatName => 'DC',
        Struct   => {
            STRUCT_NAME                         => 'DarwinCore DCTermsLocation',
            NAMESPACE                           => 'dwc',
            continent                           => {},
            coordinatePrecision                 => {},
            coordinateUncertaintyInMeters       => {},
            country                             => {},
            countryCode                         => {},
            county                              => {},
            decimalLatitude                     => {},
            decimalLongitude                    => {},
            footprintSpatialFit                 => {},
            footprintSRS                        => {},
            footprintWKT                        => {},
            geodeticDatum                       => {},
            georeferencedBy                     => {},
            georeferencedDate                   => {},
            georeferenceProtocol                => {},
            georeferenceRemarks                 => {},
            georeferenceSources                 => {},
            georeferenceVerificationStatus      => {},
            higherGeography                     => {},
            higherGeographyID                   => {},
            island                              => {},
            islandGroup                         => {},
            locality                            => {},
            locationAccordingTo                 => {},
            locationID                          => {},
            locationRemarks                     => {},
            maximumDepthInMeters                => {},
            maximumDistanceAboveSurfaceInMeters => {},
            maximumElevationInMeters            => {},
            minimumDepthInMeters                => {},
            minimumDistanceAboveSurfaceInMeters => {},
            minimumElevationInMeters            => {},
            municipality                        => {},
            pointRadiusSpatialFit               => {},
            stateProvince                       => {},
            verbatimCoordinates                 => {},
            verbatimCoordinateSystem            => {},
            verbatimDepth                       => {},
            verbatimElevation                   => {},
            verbatimLatitude                    => {},
            verbatimLocality                    => {},
            verbatimLongitude                   => {},
            verbatimSRS                         => {},
            waterBody                           => {},
            verticalDatum => {},
        },
    },
);

1;

__END__

